unbind C-b
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on

set -g base-index 1;
set -g renumber-windows on;
set -g pane-base-index 1;

set -g status-style "fg=white bg=color237"
set-option -g status-right "%H:%M:%S";

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind r source-file ~/.config/tmux/tmux.conf;

unbind '%';
unbind '"';
bind '%' split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
